### ISSUE TITLE
Created frontend for filtering page

### ISSUE THREAD

**Issue by CaesarSaleh** [ganeshasapu/easyclaim#139]
Add filters to main frontend pages, for the following categories:
- Claim Amount (divide claim amount into 3 reasonable 'cups')
- Data Claim was Added

**Comment by VibhasR** [comment]
Completed successfully for the database (Historical Claims) page.



![Image](https://github.com/ganeshasapu/easyclaim/assets/144617434/16e61a43-e517-4d70-94e8-0647baffeadf)



Have not implemented for inbox as per the fact that we realized an adjudicator should not preliminarily choose the claim amount of a claim they want to process, which may lead to bias.
