### ISSUE TITLE
Create a JSON object for each form that Glenn gave us

### ISSUE THREAD

**Issue by ganeshasapu** [ganeshasapu/easyclaim#25]
We want a JSON object that we can assume that the database contains so that we can run a similarity search on the the claims. 

Separate the forms into Life, Disability, Unemployment

Life - 3 forms
Disability - 2 forms
Unemployment - 1 form

Look through each of the forms and take the **structured** data and make it into a JSON object

By the end we should have 6 JSON objects, 1 for each form

### Still need to make some updates

**Nauhar is doing the life forms**

**Comment by VibhasR** [comment]
disability claim is done

**Comment by VibhasR** [comment]
employer claim is done

**Comment by VibhasR** [comment]
some edits to make collaboratively before closing off the ticket

:)
